function CLalpha3_simp_deriv2 = C_Lalpha3_Derivative(alpha,a,b,c,d)
%C_Lalpha3_Derivative
%    CLalpha3_simp_deriv2 = C_Lalpha3_Derivative(ALPHA,A,B,C,D)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    11-Aug-2025 14:54:42

t2 = alpha.*b;
t3 = alpha.*c;
t4 = -t2;
t5 = exp(t4);
CLalpha3_simp_deriv2 = cos(alpha.*2.0).*(1.9e+1./1.0e+1)+a.*c.*t5.*cos(t3)-a.*b.*t5.*sin(t3);
end
